[2024-12-02T15:33:26.181+0000] {processor.py:186} INFO - Started process (PID=260) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:33:26.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:33:26.184+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:33:26.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:33:26.209+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:33:26.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:33:26.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:33:26.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.054 seconds
[2024-12-02T15:33:47.503+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:33:47.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:33:47.505+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:33:47.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:33:47.531+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:33:47.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:33:47.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:33:47.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.050 seconds
[2024-12-02T15:34:17.917+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:34:17.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:34:17.919+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:34:17.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:34:17.932+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:34:17.929+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:34:17.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:34:17.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.033 seconds
[2024-12-02T15:34:48.280+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:34:48.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:34:48.283+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:34:48.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:34:48.297+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:34:48.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:34:48.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:34:48.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.036 seconds
[2024-12-02T15:35:18.649+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:35:18.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:35:18.651+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:35:18.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:35:18.667+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:35:18.664+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:35:18.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:35:18.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.042 seconds
[2024-12-02T15:35:48.989+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:35:48.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:35:48.991+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:35:48.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:35:49.007+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:35:49.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:35:49.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:35:49.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.042 seconds
[2024-12-02T15:36:19.303+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:36:19.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:36:19.306+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:36:19.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:36:19.320+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:36:19.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:36:19.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:36:19.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.038 seconds
[2024-12-02T15:36:49.618+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:36:49.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:36:49.620+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:36:49.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:36:49.636+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:36:49.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:36:49.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:36:49.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.046 seconds
[2024-12-02T15:37:19.971+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:37:19.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:37:19.974+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:37:19.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:37:19.993+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:37:19.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:37:19.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:37:20.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.046 seconds
[2024-12-02T15:37:50.352+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:37:50.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:37:50.354+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:37:50.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:37:50.366+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:37:50.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:37:50.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:37:50.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.032 seconds
[2024-12-02T15:38:20.714+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:38:20.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:38:20.716+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:38:20.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:38:20.729+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:38:20.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:38:20.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:38:20.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.035 seconds
[2024-12-02T15:38:51.114+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:38:51.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:38:51.116+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:38:51.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:38:51.130+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:38:51.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:38:51.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:38:51.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.039 seconds
[2024-12-02T15:39:21.506+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:39:21.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:39:21.508+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:39:21.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:39:21.521+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:39:21.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:39:21.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:39:21.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.033 seconds
[2024-12-02T15:39:51.854+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:39:51.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:39:51.855+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:39:51.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:39:51.870+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:39:51.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:39:51.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:39:51.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.034 seconds
[2024-12-02T15:40:22.255+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:40:22.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:40:22.257+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:40:22.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:40:22.269+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:40:22.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:40:22.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:40:22.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.036 seconds
[2024-12-02T15:40:52.592+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:40:52.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:40:52.600+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:40:52.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:40:52.621+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:40:52.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:40:52.622+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:40:52.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.053 seconds
[2024-12-02T15:41:22.962+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:41:22.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:41:22.965+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:41:22.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:41:22.984+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:41:22.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:41:22.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:41:23.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.053 seconds
[2024-12-02T15:41:53.332+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:41:53.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:41:53.334+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:41:53.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:41:53.353+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:41:53.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:41:53.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:41:53.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.043 seconds
[2024-12-02T15:42:23.653+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:42:23.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:42:23.655+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:42:23.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:42:23.670+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:42:23.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:42:23.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:42:23.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.041 seconds
[2024-12-02T15:42:54.033+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:42:54.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:42:54.035+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:42:54.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:42:54.052+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:42:54.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:42:54.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:42:54.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.041 seconds
[2024-12-02T15:43:24.375+0000] {processor.py:186} INFO - Started process (PID=399) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:24.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:43:24.378+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:24.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:24.391+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:24.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:43:24.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:24.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.037 seconds
[2024-12-02T15:43:29.472+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:29.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:43:29.475+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:29.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:29.498+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:29.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 39, in <module>
    geolocation_task = PythonOperator(
                       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 222, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 938, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to PythonOperator (task_id: train). Invalid arguments were:
**kwargs: {'tesk_id': 'geolocation'}
[2024-12-02T15:43:29.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:29.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.087 seconds
[2024-12-02T15:43:32.577+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:32.578+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:43:32.579+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:32.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:32.610+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:32.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:43:32.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:32.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.056 seconds
[2024-12-02T15:43:36.724+0000] {processor.py:186} INFO - Started process (PID=408) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:36.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:43:36.726+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:36.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:36.771+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:43:36.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:43:36.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:43:36.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.146 seconds
[2024-12-02T15:44:07.050+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:44:07.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:44:07.051+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:44:07.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:44:07.065+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:44:07.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:44:07.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:44:07.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.035 seconds
[2024-12-02T15:44:37.369+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/train_test_model.py
[2024-12-02T15:44:37.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/train_test_model.py for tasks to queue
[2024-12-02T15:44:37.371+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:44:37.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:44:37.390+0000] {logging_mixin.py:190} INFO - [2024-12-02T15:44:37.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/train_test_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_test_model.py", line 50, in <module>
    train >> test
    ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2024-12-02T15:44:37.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/train_test_model.py
[2024-12-02T15:44:37.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/train_test_model.py took 0.050 seconds
